[package]
name = "libmosquitto-sys"
version = "0.1.0"
authors = ["Wez Furlong"]
edition = "2018"
links = "mosquitto"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
pkg-config = "0.3"
