[package]
name = "mosquitto-rs"
version = "0.2.0"
authors = ["Wez Furlong"]
edition = "2018"
readme = "README.md"
license = "MIT"
description = "Unsafe FFI bindings to libmosquitto"
documentation = "https://docs.rs/mosquitto-rs"
repository = "https://github.com/wez/mosquitto-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-channel = "1.5"
downcast-rs = "1.2"
lazy_static = "1.4"
libc = "0.2"
libmosquitto-sys = {version="0.1", path="../libmosquitto-sys" }
thiserror = "1.0"

[dev-dependencies]
smol = "1.2"
