[package]
name = "mosquitto-rs"
version = "0.1.0"
authors = ["Wez Furlong"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
libmosquitto-sys = {version="0.1", path="../libmosquitto-sys" }
