name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        sudo -n apt-get update
        sudo -n apt-get install -y mosquitto-dev
    - name: Build
      run: cargo build --all --verbose
    - name: Examples
      run: cargo build --all --verbose --examples
    - name: Run tests
      run: cargo test --all --verbose
    - name: Check formatting
      run: cargo fmt --all -- --check
